
abstract=
ontologyTitle=The Emissions lnventory Ontology
ontologyPrefix=eio
ontologyNamespaceURI=http://w3id.org/def/emissionsInventoryOntology#
ontologyName=The Emissions lnventory Ontology
thisVersionURI=http://w3id.org/def/emissionsInventoryOntology/1.0.0
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=1.0.0
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=Edgar Alexis Martínez, Lucía Sánchez-González, Oscar Corcho. The Emissions lnventory Ontology. Revision: 1.0.0. Retrieved from: http://w3id.org/def/emissionsInventoryOntology/1.0.0
DOI=
status=Ontology Specification Draft
logo=
description=City-level environmental and climate ontology for Local Green Deal.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Edgar Alexis Martínez;Lucía Sánchez-González;Oscar Corcho
authorsURI=;;
authorsInstitution=;;
authorsInstitutionURI=;;
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
